name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -e .[dev]
      - name: Ruff lint
        run: |
          source .venv/bin/activate
          ruff check .
      - name: Ruff format check
        run: |
          source .venv/bin/activate
          ruff format --check .
      - name: Type check
        run: |
          source .venv/bin/activate
          mypy src tests
      - name: Run tests
        env:
          OPENAI_API_KEY: dummy
        run: |
          source .venv/bin/activate
          pytest
